Repository DCC-Lab/RayTracing, pull requests merged in 2020-06, with the labels that each got.

#221 updated documentation for gaussianbeam.py
  raytracing/gaussianbeam.py
Labels: before publication

#220 GaussianBeam: check inputs in init
  raytracing/gaussianbeam.py
  raytracing/tests/testsGaussian.py
Labels: enhancement

#223 Fix Matrix's hasPower
  raytracing/matrix.py
  raytracing/tests/testsMatrix.py
Labels: bug

#228 Finish tests GaussianBeam
  raytracing/gaussianbeam.py
  raytracing/tests/testsGaussian.py
  raytracing/tests/testsMaterials.py
  raytracing/tests/testsMatrix.py
Labels: before publication

#235 Rework tests of save/load Rays
  raytracing/tests/testsRays.py
Labels: aesthetic

#225 MatrixGroup: save setup
  raytracing/matrixgroup.py
  raytracing/rays.py
  raytracing/tests/testsMatrixGroup.py
  raytracing/tests/testsRays.py
Labels: enhancement

#237 Tests cleanup
  raytracing/imagingpath.py
  raytracing/tests/testsImagingPath.py
  raytracing/tests/testsLagrangeInvariant.py
  raytracing/tests/testsLaserPath.py
  raytracing/tests/testsLens.py
  raytracing/tests/testsLimits.py
  raytracing/tests/testsMatrix.py
  raytracing/tests/testsMatrixGroup.py
  raytracing/tests/testsMatrixSubclasses.py
  raytracing/tests/testsMultiprocessor.py
  raytracing/tests/testsRay.py
  raytracing/tests/testsRays.py
  raytracing/tests/testsRaysSubclasses.py
Labels: aesthetic, before publication

#232 Intermediate redesign of display
  raytracing/figure.py
  raytracing/imagingpath.py
  raytracing/matrix.py
  raytracing/tests/testMatrixAxesToDataScale.py
  raytracing/tests/testsFigure.py
  raytracing/tests/testsImagingPath.py
  raytracing/tests/testsMatrix.py
  raytracing/tests/testsMatrixGroup.py
  raytracing/tests/testsMultiprocessor.py
  raytracing/tests/testsRays.py
Labels: before publication

#241 Fixing two tests on Darwin with multiprocessor and matplotlib on Catalina
  raytracing/rays.py
  raytracing/tests/testsMatrix.py
  raytracing/tests/testsMultiprocessor.py
  raytracing/tests/testsRaysSubclasses.py
Labels: invalid

#244 Fixe the test that check if a warning is printed when we generate rays for more than 3 seconds
  raytracing/tests/testsRaysSubclasses.py
Labels: bug

#236 Get, set and other new methods in MatrixGroup
  raytracing/matrixgroup.py
  raytracing/tests/testsMatrixGroup.py
Labels: enhancement

#247 Finish work on MatrixGroup setitem, insert, etc
  raytracing/matrixgroup.py
  raytracing/tests/testsMatrixGroup.py
Labels: bug

#246 New design parameters
  raytracing/figure.py
  raytracing/imagingpath.py
  raytracing/tests/testsFigure.py
  raytracing/tests/testsImagingPath.py
Labels: enhancement

#253 Fix examples directory
  examples/confocalDetection.py
  examples/envexamples.py
  examples/widefield.py
  raytracing/rays.py
Labels: examples

#248 Do not limit object to FOV if object height was set by user
  raytracing/figure.py
  raytracing/imagingpath.py
Labels: before publication, enhancement

#259 Fix issue #186: ignore images out of the optical path in displayRange
  raytracing/figure.py
  raytracing/tests/testsFigure.py
Labels: bug

#258 Fixed issue with duplicates in intermediateConjugates
  raytracing/matrixgroup.py
  raytracing/tests/testsMatrixGroup.py
Labels: before publication, bug

#262 Added documentation to new methods (pop, insert, etc) + minor modifications
  raytracing/matrixgroup.py
Labels: aesthetic, before publication

#267 Doc: raw strings when "printing" matrices or rays
  raytracing/imagingpath.py
  raytracing/matrix.py
  raytracing/matrixgroup.py
Labels: aesthetic

#265 Fixed Figure to use the correct nomenclature for principalRay and axial
  raytracing/figure.py
  raytracing/imagingpath.py
  raytracing/tests/testsImagingPath.py
Labels: bug

#255 Update imagingpath.py
  raytracing/imagingpath.py
Labels: bug

#273 Matrix product has the right indices
  raytracing/matrix.py
  raytracing/tests/testsMatrix.py
Labels: before publication, bug, invalid

#278 Matrix equality
  raytracing/matrix.py
  raytracing/tests/testsMatrix.py
  raytracing/tests/testsMatrixGroup.py
Labels: enhancement

#277 Fixed tests that were failing after checking if a matrix has valid values
  .idea/other.xml
  raytracing/matrix.py
  raytracing/tests/testsMatrix.py
  raytracing/tests/testsMatrixGroup.py
Labels: before publication, bug

#261 LaserPath separated into LaserPath and LaserCavity
  raytracing/__init__.py
  raytracing/figure.py
  raytracing/gaussianbeam.py
  raytracing/lasercavity.py
  raytracing/laserpath.py
  raytracing/matrixgroup.py
  raytracing/tests/testsGaussian.py
  raytracing/tests/testsLaserPath.py
Labels: bug

#282 No negative or null aperture diameters
  raytracing/matrix.py
  raytracing/tests/testsMatrix.py
Labels: before publication, invalid

#285 Name conflict between save (MatrixGroup elements) and save (ImagingPath's figure) is no more
  examples/demo.py
  examples/illuminator.py
  examples/invariant.py
  raytracing/__main__.py
  raytracing/imagingpath.py
  raytracing/tests/testsImagingPath.py
Labels: before publication, invalid

#280 Fix display of demos
  raytracing/__main__.py
  raytracing/figure.py
  raytracing/gaussianbeam.py
  raytracing/lasercavity.py
  raytracing/laserpath.py
  raytracing/matrix.py
  raytracing/specialtylenses.py
  raytracing/tests/testsFigure.py
  raytracing/tests/testsGaussian.py
Labels: before publication, bug

#288 Ray: fanGroup and fan are deprecated.
  raytracing/ray.py
Labels: aesthetic, before publication

#293 Axicon is fully tested and fixed some problems
  raytracing/axicon.py
  raytracing/tests/testsAxicon.py
  raytracing/tests/testsMatrixGroup.py
Labels: before publication, bug, invalid

#296 Fix traceManyThroughInParallel progress display
  raytracing/matrix.py
  raytracing/tests/testCallOtherScript.py
  raytracing/tests/testsMatrix.py
  raytracing/tests/testsMultiprocessor.py
  raytracing/tests/traceManyThroughInParallelNoOutput.py
  raytracing/tests/traceManyThroughInParallelWithOutput.py
Labels: before publication, enhancement
