Repository DCC-Lab/RayTracing, pull requests merged in 2020-05, with the labels that each got.

#72 traceManyThroughInParallel is now returning Rays of Ray objects
  raytracing/matrix.py
Labels: before publication, bug

#95 Backward conjugate in entrance pupil raised AttributeError
  raytracing/imagingpath.py
  raytracing/tests/testsImagingPath.py
Labels: before publication, bug

#98 Fixed issue #97
  raytracing/ray.py
  raytracing/tests/testsRay.py
Labels: before publication, bug

#118 Empty matrixGroup now returns 'infinity' as largest diameter
  raytracing/matrixgroup.py
  raytracing/tests/testsMatrixGroup.py
Labels: before publication, bug

#124 Relative imports in __main__.py and __init__.py
  raytracing/__init__.py
  raytracing/__main__.py
Labels: invalid

#128 Matrix's forwardConjugate and backwardConjugate seem more coherent
  raytracing/matrix.py
  raytracing/tests/testsMatrix.py
Labels: question

#130 Removed useless redefinition of len() and 'if self.rays is None, if self.rays is not None' verifications
  raytracing/rays.py
Labels: aesthetic

#133 Fixed problems with Rays histogram methods
  raytracing/rays.py
  raytracing/tests/testsRays.py
Labels: before publication, bug

#137 Swap thetaMax and thetaMin in LambertianRays
  raytracing/rays.py
Labels: aesthetic

#142 Fully tested components
  raytracing/tests/testsComponents.py
Labels: before publication

#141 Changed to NotImplementedError in RandomRays
  raytracing/rays.py
  raytracing/tests/testsRaysSubclasses.py
Labels: before publication, bug

#135 Rays only accepts interables of Ray instances
  raytracing/rays.py
  raytracing/tests/testsRays.py
Labels: before publication, bug

#150 Example widefield microscope #138
  examples/widefield.py
Labels: before publication

#155 We must specifically insert the directory that includes the working copy of raytracing
  examples/demo.py
  examples/envexamples.py
  examples/exemple.py
  examples/illuminator.py
  examples/invariant.py
  examples/multiProcessingTracing.py
  examples/testTracing.py
  examples/widefield.py
Labels: bug

#157 MatrixGroup input check
  raytracing/matrixgroup.py
  raytracing/tests/testsMatrixGroup.py
Labels: before publication, bug, enhancement

#131 testsMaterials
  raytracing/materials.py
  raytracing/tests/testsMaterials.py
Labels: aesthetic, before publication, good first issue

#173 Fixed properties
  raytracing/imagingpath.py
  raytracing/matrix.py
  raytracing/matrixgroup.py
  raytracing/specialtylenses.py
  raytracing/tests/testsMatrix.py
  raytracing/tests/testsMatrixGroup.py
  raytracing/tests/testsMatrixSubclasses.py
Labels: enhancement

#174 Ray, Rays and subclasses are tested.
  raytracing/rays.py
  raytracing/tests/testsRay.py
  raytracing/tests/testsRays.py
  raytracing/tests/testsRaysSubclasses.py
Labels: before publication

#176 Load check if the content of the loaded file is iterable and contains only Ray instances
  raytracing/rays.py
  raytracing/tests/testsRays.py
Labels: before publication, bug, enhancement

#180 Fixed eigenModes and laserModes
  raytracing/laserpath.py
  raytracing/tests/testsLaserPath.py
Labels: before publication, bug

#185 Tests for LaserPath
  raytracing/laserpath.py
  raytracing/tests/testsLaserPath.py
Labels: before publication

#187 Proposition (can somewhat fix problem with ImagingPath and LaserPath methods in MatrixGroup)
  raytracing/matrixgroup.py
  raytracing/tests/testsMatrixGroup.py
Labels: before publication, bug, enhancement, invalid

#192 Fix chief ray with no aperture stop (ImaginPath)
  raytracing/imagingpath.py
  raytracing/tests/testsImagingPath.py
Labels: before publication, bug

#195 Update imagingpath.py
  raytracing/imagingpath.py
Labels: bug

#196 ImageSize of ImagingPath returns inf when there is no forward conjugate
  raytracing/imagingpath.py
  raytracing/tests/testsImagingPath.py
Labels: before publication, bug

#204 Fix margial rays when B is 0
  raytracing/imagingpath.py
  raytracing/tests/testsImagingPath.py
Labels: before publication, bug

#202 Fix marginal rays when no aperture stop
  raytracing/imagingpath.py
  raytracing/tests/testsImagingPath.py
Labels: before publication, bug

#200 ChiefRay raises exception when no y and infinite field of view
  raytracing/imagingpath.py
  raytracing/tests/testsImagingPath.py
Labels: before publication, bug

#199 Fix chiefRay when B is close to 0 (but not 0)
  raytracing/imagingpath.py
  raytracing/tests/testsImagingPath.py
Labels: before publication, bug

#206 ImagingPath: 99% coverage
  raytracing/imagingpath.py
  raytracing/tests/testsImagingPath.py
  raytracing/tests/testsLagrangeInvariant.py
Labels: before publication

#213 issue#120_NewSpecialtyLensType
  docs/contribute.md
  docs/contribute.rst
  docs/index.rst
  docs/modules/LambertianRays.png
  docs/modules/RandomLambertianRays.png
  docs/modules/RandomUniformRays.png
  docs/modules/UniformRays.png
  docs/modules/methods/Rays/AngleHist.png
  docs/modules/methods/Rays/Histogram.png
  docs/modules/methods/Rays/UniformRays.png
  docs/modules/methods/Rays/displayRays.png
  raytracing/eo.py
  raytracing/imagingpath.py
  raytracing/materials.py
  raytracing/ray.py
  raytracing/rays.py
  raytracing/specialtylenses.py
  raytracing/tests/testsSpecialLenses.py
  raytracing/tests/testsSpecialtyLenses.py
  raytracing/thorlabs.py
Labels: before publication, enhancement

#210 issue#120_testsSpecialtyLenses merge with Master
  raytracing/eo.py
  raytracing/materials.py
  raytracing/specialtylenses.py
  raytracing/tests/testsSpecialLenses.py
  raytracing/tests/testsSpecialtyLenses.py
  raytracing/thorlabs.py
Labels: before publication

#207 Proposition: displayRange deals in absolute values
  examples/demo.py
  raytracing/__main__.py
  raytracing/imagingpath.py
  raytracing/tests/testsImagingPath.py
Labels: bug, enhancement
