Repository DCC-Lab/RayTracing, pull requests merged in 2020-07, with the labels that each got.

#306 Deprecated decorator
  raytracing/ray.py
  raytracing/tests/testsDecorators.py
  raytracing/utils.py
Labels: aesthetic, enhancement

#300 Lagrange and optical invariant improvements
  docs/README-documentation.md
  examples/widefield.py
  raytracing/__init__.py
  raytracing/axicon.py
  raytracing/figure.py
  raytracing/imagingpath.py
  raytracing/matrix.py
  raytracing/matrixgroup.py
  raytracing/olympus.py
  raytracing/rays.py
  raytracing/specialtylenses.py
  raytracing/tests/TestModule.py
  raytracing/tests/envtest.py
  raytracing/tests/testsCallOtherScript.py
  raytracing/tests/testsEnvtest.py
  raytracing/tests/testsImagingPath.py
  raytracing/tests/testsLagrangeInvariantIdeas.py
  raytracing/tests/testsMaterials.py
  raytracing/tests/testsMatrix.py
  raytracing/tests/testsRays.py
  raytracing/tests/testsRaysSubclasses.py
  raytracing/tests/testsSpecialtyLenses.py
Labels: before publication, bug

#303 Laser scanning microscope
  examples/lagrangeAndEfficiencyElahe.py
  examples/laserScanningMicroscope.py
  raytracing/tests/testsDocTestModule.py
Labels: before publication, examples

#312 Achromats take wavelenght argument and corrects focal for used wavelenght
  raytracing/ray.py
  raytracing/specialtylenses.py
  raytracing/tests/testsSpecialtyLenses.py
  raytracing/thorlabs.py
Labels: enhancement

#319 Tests for infinite conjugates
  raytracing/tests/testsMatrix.py
  raytracing/tests/testsRays.py
  raytracing/utils.py
Labels: bug

#313 Change max Invariant symbol to make it correspond to the article
  raytracing/imagingpath.py
Labels: aesthetic

#310 laserScanningMicroscope.py Deleted first graph and rearranged some variables.
  examples/laserScanningMicroscope.py
Labels: examples

#318 Display with object & interactivity
  examples/sourceCollection.py
  raytracing/__main__.py
  raytracing/figure.py
  raytracing/graphicComponents.py
  raytracing/graphics.py
  raytracing/imagingpath.py
Labels: aesthetic, before publication

#330 Valerie - invariant and efficiency example
  examples/invariantAndEfficiency.py
Labels: examples

#329 Kohler example!
  examples/Kohler.py
  examples/KohlerAndInvariant.py
Labels: examples
